base_url = "https://babl.ws"
title = "Babl - High Performance WebSocket Server"
description = ""
default_language = "en"
theme = "book"
build_search_index = false
highlight_code = true
generate_rss = false
highlight_theme = "solarized-light"

[extra]
book_number_chapters = false