version: '3'
services:
  http_host:
    image: "nginx:latest"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    hostname: babl-proxy
    networks:
      mgt:
        ipv4_address: 172.30.2.2
    ports:
      - "8020:8020"
  babl-server:
    image: "aitusoftware/babl-example:latest"
    hostname: babl-server
    volumes:
      - server-data-dir:/babl/server
    ports:
      - "8080:8080"
    networks:
      mgt:
        ipv4_address: 172.30.2.3
  babl-error-monitor:
    image: "aitusoftware/babl-error-printer:latest"
    hostname: babl-error-monitor
    volumes:
      - server-data-dir:/babl/server
  babl-stats-monitor:
    image: "aitusoftware/babl-monitoring:latest"
    hostname: babl-stats-monitor
    volumes:
      - server-data-dir:/babl/server

volumes:
  server-data-dir:
networks:
  mgt:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: 'false'
    ipam:
      driver: default
      config:
        - subnet: 172.30.2.0/24
